/*
 * This file was autogenerated
 * DO NOT EDIT
 * (C) 2015-2016 Renesas Electronics Europe, LTD
 */

#ifndef __PINCTRL_RZN1_H__
#define __PINCTRL_RZN1_H__

#define RZN1_MUX_FUNC_BIT			8
#define RZN1_MUX_HAS_FUNC_BIT			15
#define RZN1_MUX_HAS_DRIVE_BIT			16
#define RZN1_MUX_DRIVE_BIT			17
#define RZN1_MUX_HAS_PULL_BIT			19
#define RZN1_MUX_PULL_BIT			20
#define RZN1_MUX_HAS_RGMII_BIT			22
#define RZN1_MUX_RGMII_BIT			23

#define RZN1_MUX(_gpio, _func) \
	(((RZN1_FUNC_##_func) << RZN1_MUX_FUNC_BIT) | \
		(1 << RZN1_MUX_HAS_FUNC_BIT) | \
		(_gpio))

#define RZN1_FUNC_HIGHZ				0
#define RZN1_FUNC_0L				1
#define RZN1_FUNC_CLK_ETH_MII_RGMII_RMII	2
#define RZN1_FUNC_CLK_ETH_NAND			3
#define RZN1_FUNC_QSPI				4
#define RZN1_FUNC_SDIO				5
#define RZN1_FUNC_LCD				6
#define RZN1_FUNC_LCD_E				7
#define RZN1_FUNC_MSEBIM			8
#define RZN1_FUNC_MSEBIS			9
#define RZN1_FUNC_LEVEL2_OFFSET			10	/* I'm Special */
#define RZN1_FUNC_HIGHZ1			10
#define RZN1_FUNC_ETHERCAT			11
#define RZN1_FUNC_SERCOS3			12
#define RZN1_FUNC_SDIO_E			13
#define RZN1_FUNC_ETH_MDIO			14
#define RZN1_FUNC_ETH_MDIO_E1			15
#define RZN1_FUNC_USB				16
#define RZN1_FUNC_MSEBIM_E			17
#define RZN1_FUNC_MSEBIS_E			18
#define RZN1_FUNC_XBUS				19
#define RZN1_FUNC_XBUS_E			20
#define RZN1_FUNC_XBUS_E1			21
#define RZN1_FUNC_UART0_I			22
#define RZN1_FUNC_UART0_I_E			23
#define RZN1_FUNC_UART1_I			24
#define RZN1_FUNC_UART1_I_E			25
#define RZN1_FUNC_UART2_I			26
#define RZN1_FUNC_UART2_I_E			27
#define RZN1_FUNC_UART0				28
#define RZN1_FUNC_UART0_E			29
#define RZN1_FUNC_UART1				30
#define RZN1_FUNC_UART1_E			31
#define RZN1_FUNC_UART2				32
#define RZN1_FUNC_UART2_E			33
#define RZN1_FUNC_UART3				34
#define RZN1_FUNC_UART3_E			35
#define RZN1_FUNC_UART4				36
#define RZN1_FUNC_UART4_E			37
#define RZN1_FUNC_UART5				38
#define RZN1_FUNC_UART5_E			39
#define RZN1_FUNC_UART6				40
#define RZN1_FUNC_UART6_E			41
#define RZN1_FUNC_UART7				42
#define RZN1_FUNC_UART7_E			43
#define RZN1_FUNC_SPI0_M			44
#define RZN1_FUNC_SPI0_M_E			45
#define RZN1_FUNC_SPI1_M			46
#define RZN1_FUNC_SPI1_M_E			47
#define RZN1_FUNC_SPI2_M			48
#define RZN1_FUNC_SPI2_M_E			49
#define RZN1_FUNC_SPI3_M			50
#define RZN1_FUNC_SPI3_M_E			51
#define RZN1_FUNC_SPI4_S			52
#define RZN1_FUNC_SPI4_S_E			53
#define RZN1_FUNC_SPI5_S			54
#define RZN1_FUNC_SPI5_S_E			55
#define RZN1_FUNC_SGPIO0_M			56
#define RZN1_FUNC_SGPIO1_M			57
#define RZN1_FUNC_GPIO				58
#define RZN1_FUNC_CAN				59
#define RZN1_FUNC_I2C				60
#define RZN1_FUNC_SAFE				61
#define RZN1_FUNC_PTO_PWM			62
#define RZN1_FUNC_PTO_PWM1			63
#define RZN1_FUNC_PTO_PWM2			64
#define RZN1_FUNC_PTO_PWM3			65
#define RZN1_FUNC_PTO_PWM4			66
#define RZN1_FUNC_DELTA_SIGMA			67
#define RZN1_FUNC_SGPIO2_M			68
#define RZN1_FUNC_SGPIO3_M			69
#define RZN1_FUNC_SGPIO4_S			70
#define RZN1_FUNC_MAC_MTIP_SWITCH		71
#define RZN1_FUNC_MAX				72

#define RZN1_FUNC_NONE				0xff


#endif /* __PINCTRL_RZN1_H__ */
