/*
 * This file was autogenerated
 * DO NOT EDIT
 * (C) 2015-2016 Renesas Electronics Europe, LTD
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __RZN1_CLKCTRL_TABLES_H__
#define __RZN1_CLKCTRL_TABLES_H__

#define RZN1_CLK_COUNT		127

static const struct rzn1_clkdesc rzn1_clock_list[RZN1_CLK_COUNT] = {
	[RZN1_CLK_HOST_SDIO0_ID] =
		_CLK("clk_host_sdio0",	_BIT(3, 0), _BIT(3, 1), _BIT(3, 2), _BIT(3, 3), _BIT(4, 0), _BIT(4, 1), _BIT(4, 2)),
	[RZN1_CLK_XIN_SDIO0_ID] =
		_CLK("clk_xin_sdio0",	_BIT(3, 4), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_USBH_ID] =
		_CLK("clk_usbh",	_BIT(7, 0), _BIT(7, 1), {}, _BIT(7, 2), {}, _BIT(8, 0), _BIT(8, 1)),
	[RZN1_CLK_USBF_ID] =
		_CLK("clk_usbf",	_BIT(7, 3), {}, {}, _BIT(7, 4), {}, _BIT(8, 2), _BIT(8, 3)),
	[RZN1_CLK_USBPM_ID] =
		_CLK("clk_usbpm",	_BIT(7, 5), {}, {}, {}, {}, {}, {}),
	[RZN1_PCLK_PCI_USB_ID] =
		_CLK("pclk_pci_usb",	_BIT(7, 6), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_CRYPTO_EIP93_ID] =
		_CLK("clk_crypto_eip93",	_BIT(9, 0), _BIT(9, 1), {}, _BIT(9, 2), {}, _BIT(10, 0), _BIT(10, 1)),
	[RZN1_CLK_CRYPTO_AXI_ID] =
		_CLK("clk_crypto_axi",	_BIT(9, 3), _BIT(9, 4), _BIT(9, 5), {}, _BIT(10, 2), {}, {}),
	[RZN1_CLK_MSEBIS_ID] =
		_CLK("clk_msebis",	_BIT(11, 0), _BIT(11, 1), _BIT(11, 2), _BIT(11, 3), _BIT(12, 0), _BIT(12, 1), _BIT(12, 2)),
	[RZN1_CLK_MSEBIM_ID] =
		_CLK("clk_msebim",	_BIT(11, 4), _BIT(11, 5), _BIT(11, 6), {}, _BIT(12, 3), {}, {}),
	[RZN1_PCLK_UART0_ID] =
		_CLK("pclk_uart0",	_BIT(13, 0), _BIT(13, 1), _BIT(13, 2), {}, {}, {}, {}),
	[RZN1_PCLK_UART1_ID] =
		_CLK("pclk_uart1",	_BIT(13, 3), _BIT(13, 4), _BIT(13, 5), {}, {}, {}, {}),
	[RZN1_PCLK_UART2_ID] =
		_CLK("pclk_uart2",	_BIT(13, 6), _BIT(13, 7), _BIT(13, 8), {}, {}, {}, {}),
	[RZN1_PCLK_I2C0_ID] =
		_CLK("pclk_i2c0",	_BIT(13, 9), _BIT(13, 10), _BIT(13, 11), {}, {}, {}, {}),
	[RZN1_PCLK_I2C1_ID] =
		_CLK("pclk_i2c1",	_BIT(13, 12), _BIT(13, 13), _BIT(13, 14), {}, {}, {}, {}),
	[RZN1_PCLK_ADC_ID] =
		_CLK("pclk_adc",	_BIT(13, 15), _BIT(13, 16), _BIT(13, 17), {}, {}, {}, {}),
	[RZN1_SCLK_UART0_ID] =
		_CLK("sclk_uart0",	_BIT(13, 18), _BIT(13, 19), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART0_ID] =
		_CLK("sclk_usb_uart0",	_BIT(13, 20), _BIT(13, 21), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART1_ID] =
		_CLK("sclk_uart1",	_BIT(13, 22), _BIT(13, 23), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART1_ID] =
		_CLK("sclk_usb_uart1",	_BIT(13, 24), _BIT(13, 25), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART2_ID] =
		_CLK("sclk_uart2",	_BIT(13, 26), _BIT(13, 27), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART2_ID] =
		_CLK("sclk_usb_uart2",	_BIT(13, 28), _BIT(13, 29), {}, {}, {}, {}, {}),
	[RZN1_CLK_IC_I2C0_ID] =
		_CLK("clk_ic_i2c0",	_BIT(15, 6), _BIT(15, 7), {}, {}, {}, {}, {}),
	[RZN1_CLK_IC_I2C1_ID] =
		_CLK("clk_ic_i2c1",	_BIT(15, 8), _BIT(15, 9), {}, {}, {}, {}, {}),
	[RZN1_CLK_ADC_ID] =
		_CLK("clk_adc",		_BIT(15, 10), _BIT(15, 11), {}, {}, {}, {}, {}),
	[RZN1_CLK_SGPIO0_ID] =
		_CLK("clk_sgpio0",	_BIT(15, 0), _BIT(15, 1), _BIT(15, 2), {}, {}, {}, {}),
	[RZN1_CLK_SGPIO1_ID] =
		_CLK("clk_sgpio1",	_BIT(15, 3), _BIT(15, 4), _BIT(15, 5), {}, {}, {}, {}),
	[RZN1_CLK_PWM_PTO_ID] =
		_CLK("clk_pwm_pto",	_BIT(15, 12), _BIT(15, 13), _BIT(15, 14), {}, {}, {}, {}),
	[RZN1_CLK_DELTASIGMA_ID] =
		_CLK("clk_deltasigma",	_BIT(15, 15), _BIT(15, 16), _BIT(15, 17), {}, {}, {}, {}),
	[RZN1_PCLK_SPI0_ID] =
		_CLK("pclk_spi0",	_BIT(16, 0), _BIT(16, 1), _BIT(16, 2), {}, {}, {}, {}),
	[RZN1_PCLK_SPI1_ID] =
		_CLK("pclk_spi1",	_BIT(16, 3), _BIT(16, 4), _BIT(16, 5), {}, {}, {}, {}),
	[RZN1_PCLK_SPI2_ID] =
		_CLK("pclk_spi2",	_BIT(16, 6), _BIT(16, 7), _BIT(16, 8), {}, {}, {}, {}),
	[RZN1_PCLK_SPI3_ID] =
		_CLK("pclk_spi3",	_BIT(16, 9), _BIT(16, 10), _BIT(16, 11), {}, {}, {}, {}),
	[RZN1_PCLK_SPI4_ID] =
		_CLK("pclk_spi4",	_BIT(16, 12), _BIT(16, 13), _BIT(16, 14), {}, {}, {}, {}),
	[RZN1_PCLK_SPI5_ID] =
		_CLK("pclk_spi5",	_BIT(16, 15), _BIT(16, 16), _BIT(16, 17), {}, {}, {}, {}),
	[RZN1_PCLK_GPIO0_ID] =
		_CLK("pclk_gpio0",	_BIT(16, 18), _BIT(16, 19), _BIT(16, 20), {}, {}, {}, {}),
	[RZN1_PCLK_GPIO1_ID] =
		_CLK("pclk_gpio1",	_BIT(16, 21), _BIT(16, 22), _BIT(16, 23), {}, {}, {}, {}),
	[RZN1_PCLK_UART3_ID] =
		_CLK("pclk_uart3",	_BIT(16, 24), _BIT(16, 25), _BIT(16, 26), {}, {}, {}, {}),
	[RZN1_PCLK_UART4_ID] =
		_CLK("pclk_uart4",	_BIT(16, 27), _BIT(16, 28), _BIT(16, 29), {}, {}, {}, {}),
	[RZN1_PCLK_UART5_ID] =
		_CLK("pclk_uart5",	_BIT(17, 0), _BIT(17, 1), _BIT(17, 2), {}, {}, {}, {}),
	[RZN1_PCLK_UART6_ID] =
		_CLK("pclk_uart6",	_BIT(17, 3), _BIT(17, 4), _BIT(17, 5), {}, {}, {}, {}),
	[RZN1_PCLK_UART7_ID] =
		_CLK("pclk_uart7",	_BIT(17, 6), _BIT(17, 7), _BIT(17, 8), {}, {}, {}, {}),
	[RZN1_CLK_GPIO2_ID] =
		_CLK("clk_gpio2",	_BIT(17, 9), _BIT(17, 10), _BIT(17, 11), {}, {}, {}, {}),
	[RZN1_CLK_UDL19_ID] =
		_CLK("clk_udl19",	_BIT(17, 12), _BIT(17, 13), _BIT(17, 14), {}, {}, {}, {}),
	[RZN1_CLK_UDL20_ID] =
		_CLK("clk_udl20",	_BIT(17, 15), _BIT(17, 16), _BIT(17, 17), {}, {}, {}, {}),
	[RZN1_HCLK_DMA0_ID] =
		_CLK("hclk_dma0",	_BIT(19, 0), _BIT(19, 1), _BIT(19, 2), _BIT(19, 3), _BIT(22, 0), _BIT(22, 1), _BIT(22, 2)),
	[RZN1_HCLK_DMA1_ID] =
		_CLK("hclk_dma1",	_BIT(19, 4), _BIT(19, 5), _BIT(19, 6), _BIT(19, 7), _BIT(22, 3), _BIT(22, 4), _BIT(22, 5)),
	[RZN1_CLKA_NAND_ID] =
		_CLK("clka_nand",	_BIT(20, 0), _BIT(20, 1), _BIT(20, 2), _BIT(20, 3), _BIT(23, 0), _BIT(23, 1), _BIT(23, 2)),
	[RZN1_CLKB_NAND_ID] =
		_CLK("clkb_nand",	_BIT(20, 4), _BIT(20, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_QSPI0_ID] =
		_CLK("clk_qspi0",	_BIT(21, 0), _BIT(21, 1), _BIT(21, 2), _BIT(21, 3), _BIT(24, 0), _BIT(24, 1), _BIT(24, 2)),
	[RZN1_CLK_REF_ID] =
		_CLK("clk_qspi0_ref",	_BIT(21, 4), _BIT(21, 5), {}, {}, {}, {}, {}),
	[RZN1_ACLK_AXIY_ID] =
		_CLK("aclk_axiy",	_BIT(25, 0), _BIT(25, 2), {}, _BIT(25, 1), {}, _BIT(29, 0), _BIT(29, 1)),
	[RZN1_CLK_DDR_ID] =
		_CLK("clk_ddr",		_BIT(25, 3), _BIT(25, 4), {}, {}, {}, {}, {}),
	[RZN1_CLK_RGMII_ID] =
		_CLK("clk_rgmii",	_BIT(26, 0), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_RMII_ID] =
		_CLK("clk_rmii",	_BIT(26, 1), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_MII_ID] =
		_CLK("clk_mii",		_BIT(26, 2), {}, {}, {}, {}, {}, {}),
	[RZN1_ACLK_MAC0_ID] =
		_CLK("aclk_mac0",	_BIT(27, 0), _BIT(27, 1), _BIT(27, 2), _BIT(27, 3), _BIT(30, 0), _BIT(30, 1), _BIT(30, 2)),
	[RZN1_ACLK_MAC1_ID] =
		_CLK("aclk_mac1",	_BIT(28, 0), _BIT(28, 1), _BIT(28, 2), _BIT(28, 3), _BIT(31, 0), _BIT(31, 1), _BIT(31, 2)),
	[RZN1_HCLK_ECAT_CLK125_ID] =
		_CLK("hclk_ecat_clk125",	_BIT(32, 0), _BIT(32, 1), {}, _BIT(32, 2), {}, _BIT(34, 0), _BIT(34, 1)),
	[RZN1_CLK25_ID] =
		_CLK("clk25",		_BIT(32, 3), _BIT(32, 4), {}, {}, {}, {}, {}),
	[RZN1_CLK100_ID] =
		_CLK("clk100",		_BIT(32, 5), {}, {}, {}, {}, {}, {}),
	[RZN1_HCLK_S3_CLK100G_ID] =
		_CLK("hclk_s3_clk100g",	_BIT(33, 0), _BIT(33, 2), {}, _BIT(33, 1), {}, _BIT(35, 0), _BIT(35, 1)),
	[RZN1_CLK_S3_CLK50_ID] =
		_CLK("clk_s3_clk50",	_BIT(33, 4), _BIT(33, 3), {}, {}, {}, {}, {}),
	[RZN1_CLK_S3_CLK100_ID] =
		_CLK("clk_s3_clk100",	_BIT(33, 5), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_QSPI1_ID] =
		_CLK("clk_qspi1",	_BIT(36, 0), _BIT(36, 1), _BIT(36, 2), _BIT(36, 3), _BIT(38, 0), _BIT(38, 1), _BIT(38, 2)),
	[RZN1_CLK_QSPI1_REF_ID] =
		_CLK("clk_qspi1_ref",	_BIT(36, 4), _BIT(36, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_HSR_DUP_ID] =
		_CLK("clk_hsr_dup",	_BIT(36, 3), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK50MHZ_ID] =
		_CLK("clk50mhz",	_BIT(36, 4), _BIT(36, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_HOST_SDIO1_ID] =
		_CLK("clk_host_sdio1",	_BIT(50, 0), _BIT(50, 1), _BIT(50, 2), _BIT(50, 3), _BIT(51, 0), _BIT(51, 1), _BIT(51, 2)),
	[RZN1_CLK_XIN_SDIO1_ID] =
		_CLK("clk_xin_sdio1",	_BIT(50, 4), {}, {}, {}, {}, {}, {}),
	[RZN1_CLK_25MHZ_UDL1_ID] =
		_CLK("clk_25mhz_udl1",	_BIT(58, 0), _BIT(58, 1), _BIT(58, 2), {}, _BIT(87, 0), {}, {}),
	[RZN1_CLK_TIMER0_ID] =
		_CLK("clk_timer0",	_BIT(58, 3), _BIT(58, 4), _BIT(58, 5), {}, _BIT(87, 1), {}, {}),
	[RZN1_CLK_TIMER1_ID] =
		_CLK("clk_timer1",	_BIT(58, 6), _BIT(58, 7), _BIT(58, 8), {}, _BIT(87, 2), {}, {}),
	[RZN1_CLK_25MHZ_UDL4_ID] =
		_CLK("clk_25mhz_udl4",	_BIT(58, 9), _BIT(58, 10), _BIT(58, 11), {}, _BIT(87, 3), {}, {}),
	[RZN1_CLK_25MHZ_UDL5_ID] =
		_CLK("clk_25mhz_udl5",	_BIT(58, 12), _BIT(58, 13), _BIT(58, 14), {}, _BIT(87, 4), {}, {}),
	[RZN1_CLK_25MHZ_UDL6_ID] =
		_CLK("clk_25mhz_udl6",	_BIT(58, 15), _BIT(58, 16), _BIT(58, 17), {}, _BIT(87, 5), {}, {}),
	[RZN1_CLK_25MHZ_UDL7_ID] =
		_CLK("clk_25mhz_udl7",	_BIT(58, 18), _BIT(58, 19), _BIT(58, 20), {}, _BIT(87, 6), {}, {}),
	[RZN1_CLK_25MHZ_UDL8_ID] =
		_CLK("clk_25mhz_udl8",	_BIT(58, 21), _BIT(58, 22), _BIT(58, 23), {}, _BIT(87, 7), {}, {}),
	[RZN1_SCLK_UART3_ID] =
		_CLK("sclk_uart3",	_BIT(59, 0), _BIT(59, 1), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART3_ID] =
		_CLK("sclk_usb_uart3",	_BIT(59, 2), _BIT(59, 3), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART4_ID] =
		_CLK("sclk_uart4",	_BIT(59, 4), _BIT(59, 5), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART4_ID] =
		_CLK("sclk_usb_uart4",	_BIT(59, 6), _BIT(59, 7), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART5_ID] =
		_CLK("sclk_uart5",	_BIT(59, 8), _BIT(59, 9), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART5_ID] =
		_CLK("sclk_usb_uart5",	_BIT(59, 10), _BIT(59, 11), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART6_ID] =
		_CLK("sclk_uart6",	_BIT(59, 12), _BIT(59, 13), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART6_ID] =
		_CLK("sclk_usb_uart6",	_BIT(59, 14), _BIT(59, 15), {}, {}, {}, {}, {}),
	[RZN1_SCLK_UART7_ID] =
		_CLK("sclk_uart7",	_BIT(59, 16), _BIT(59, 17), {}, {}, {}, {}, {}),
	[RZN1_SCLK_USB_UART7_ID] =
		_CLK("sclk_usb_uart7",	_BIT(59, 18), _BIT(59, 19), {}, {}, {}, {}, {}),
	[RZN1_CLK_NOUSBP2_UDL6_ID] =
		_CLK("clk_nousbp2_udl6",	_BIT(59, 20), _BIT(59, 21), {}, {}, {}, {}, {}),
	[RZN1_CLK_USBP2_UDL6_ID] =
		_CLK("clk_usbp2_udl6",	_BIT(59, 22), _BIT(59, 23), {}, {}, {}, {}, {}),
	[RZN1_CLK_CAN1_ID] =
		_CLK("clk_can1",	_BIT(60, 6), _BIT(60, 7), _BIT(60, 8), {}, _BIT(88, 2), {}, {}),
	[RZN1_CLK_48MHZ_UDL4_ID] =
		_CLK("clk_48mhz_udl4",	_BIT(60, 9), _BIT(60, 10), _BIT(60, 11), {}, _BIT(88, 3), {}, {}),
	[RZN1_CLK_48MHZ_UDL_F_ID] =
		_CLK("clk_48mhz_udl_f",	_BIT(60, 12), _BIT(60, 13), {}, _BIT(60, 14), {}, _BIT(88, 4), _BIT(88, 5)),
	[RZN1_CLK_RSV_ID] =
		_CLK("clk_rsv",		_BIT(60, 0), _BIT(60, 1), _BIT(60, 2), {}, _BIT(88, 0), {}, {}),
	[RZN1_CLK_CAN0_ID] =
		_CLK("clk_can0",	_BIT(60, 3), _BIT(60, 4), _BIT(60, 5), {}, _BIT(88, 1), {}, {}),
	[RZN1_CLK_LCD_ID] =
		_CLK("clk_lcd",		_BIT(61, 0), _BIT(61, 1), _BIT(61, 2), {}, _BIT(89, 0), {}, {}),
	[RZN1_CLK_SEMAP_ID] =
		_CLK("clk_semap",	_BIT(61, 3), _BIT(61, 4), _BIT(61, 5), {}, _BIT(89, 1), {}, {}),
	[RZN1_CLK_UDL3_ID] =
		_CLK("clk_udl3",	_BIT(61, 6), _BIT(61, 7), _BIT(61, 8), {}, _BIT(89, 2), {}, {}),
	[RZN1_CLK_UDL4_ID] =
		_CLK("clk_udl4",	_BIT(61, 9), _BIT(61, 10), _BIT(61, 11), {}, _BIT(89, 3), {}, {}),
	[RZN1_CLK_UDL_I_ID] =
		_CLK("clk_udl_i",	_BIT(61, 12), _BIT(61, 13), {}, _BIT(61, 14), {}, _BIT(89, 4), _BIT(89, 5)),
	[RZN1_CLK_SSI_SPI0_ID] =
		_CLK("clk_ssi_spi0",	_BIT(63, 0), _BIT(63, 1), {}, {}, {}, {}, {}),
	[RZN1_CLK_SSI_SPI1_ID] =
		_CLK("clk_ssi_spi1",	_BIT(63, 2), _BIT(63, 3), {}, {}, {}, {}, {}),
	[RZN1_CLK_SSI_SPI2_ID] =
		_CLK("clk_ssi_spi2",	_BIT(63, 4), _BIT(63, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_SSI_SPI3_ID] =
		_CLK("clk_ssi_spi3",	_BIT(63, 6), _BIT(63, 7), {}, {}, {}, {}, {}),
	[RZN1_CLK_SSI_SPI4_ID] =
		_CLK("clk_ssi_spi4",	_BIT(65, 0), _BIT(65, 1), {}, {}, {}, {}, {}),
	[RZN1_CLK_SSI_SPI5_ID] =
		_CLK("clk_ssi_spi5",	_BIT(65, 2), _BIT(65, 3), {}, {}, {}, {}, {}),
	[RZN1_CLK_P4_UDL3_ID] =
		_CLK("clk_p4_udl3",	_BIT(65, 4), _BIT(65, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_P4_UDL4_ID] =
		_CLK("clk_p4_udl4",	_BIT(65, 6), _BIT(65, 7), {}, {}, {}, {}, {}),
	[RZN1_CLK_SLCD_ID] =
		_CLK("clk_slcd",	_BIT(67, 0), _BIT(67, 1), {}, {}, {}, {}, {}),
	[RZN1_CLK_P1_UDL2_ID] =
		_CLK("clk_p1_udl2",	_BIT(67, 2), _BIT(67, 3), {}, {}, {}, {}, {}),
	[RZN1_CLK_P1_UDL3_ID] =
		_CLK("clk_p1_udl3",	_BIT(67, 4), _BIT(67, 5), {}, {}, {}, {}, {}),
	[RZN1_CLK_P1_UDL4_ID] =
		_CLK("clk_p1_udl4",	_BIT(67, 6), _BIT(67, 7), {}, {}, {}, {}, {}),
	[RZN1_CLK_P6_UDL1_ID] =
		_CLK("clk_p6_udl1",	_BIT(69, 0), _BIT(69, 1), _BIT(69, 2), {}, _BIT(91, 0), {}, {}),
	[RZN1_CLK_P6_UDL2_ID] =
		_CLK("clk_p6_udl2",	_BIT(69, 3), _BIT(69, 4), _BIT(69, 5), {}, _BIT(91, 1), {}, {}),
	[RZN1_CLK_P6_UDL3_ID] =
		_CLK("clk_p6_udl3",	_BIT(69, 6), _BIT(69, 7), _BIT(69, 8), {}, _BIT(91, 2), {}, {}),
	[RZN1_CLK_P6_UDL4_ID] =
		_CLK("clk_p6_udl4",	_BIT(69, 9), _BIT(69, 10), _BIT(69, 11), {}, _BIT(91, 3), {}, {}),
	[RZN1_CLK_SGPIO2_ID] =
		_CLK("clk_sgpio2",	_BIT(70, 3), _BIT(70, 4), _BIT(70, 5), {}, _BIT(90, 1), {}, {}),
	[RZN1_CLK_SGPIO3_ID] =
		_CLK("clk_sgpio3",	_BIT(70, 6), _BIT(70, 7), _BIT(70, 8), {}, _BIT(90, 2), {}, {}),
	[RZN1_CLK_SGPIO4_ID] =
		_CLK("clk_sgpio4",	_BIT(70, 9), _BIT(70, 10), _BIT(70, 11), {}, _BIT(90, 3), {}, {}),
	[RZN1_CLK_CPU_ID] =
		_CLK("clk_cpu",		_BIT(76, 0), {}, _BIT(76, 1), {}, {}, {}, {}),
	[RZN1_CLK_SWITCH_SX_ID] =
		_CLK("clk_switch_sx",	_BIT(76, 2), _BIT(76, 3), {}, {}, {}, {}, {}),
	[RZN1_CLK_RTC_ID] =
		_CLK("clk_rtc",		_BIT(80, 0), {}, {}, {}, {}, {}, {}),
	[RZN1_HCLK_ROM_ID] =
		_CLK("hclk_rom",	_BIT(85, 0), _BIT(85, 1), _BIT(85, 2), {}, _BIT(92, 0), {}, {}),
	[RZN1_FCLK_CM3_ID] =
		_CLK("fclk_cm3",	_BIT(93, 0), _BIT(93, 1), {}, _BIT(93, 2), {}, _BIT(94, 0), _BIT(94, 1)),
	[RZN1_HCLK_BUS_ID] =
		_CLK("hclk_bus",	_BIT(97, 0), _BIT(97, 1), _BIT(97, 2), {}, {}, {}, {}),
	[RZN1_HCLK_SWITCH_RG_ID] =
		_CLK("hclk_switch_rg",	_BIT(98, 0), _BIT(98, 1), _BIT(98, 2), {}, {}, {}, {}),
	[RZN1_CLK_RTOS_SYS_ID] =
		_CLK("clk_rtos_sys",	_BIT(99, 0), _BIT(99, 1), {}, {}, {}, {}, {}),
	[RZN1_CLK_RTOS_MDC_ID] =
		_CLK("clk_rtos_mdc",	_BIT(99, 2), {}, {}, {}, {}, {}, {}),
};


#endif /* __RZN1_CLKCTRL_TABLES_H__ */
