#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y := start.o
obj-y += cpu.o

obj-$(CONFIG_SYS_ARCH_TIMER) += systick-timer.o

# Re-use the RZ/N1 armv7 code
obj-$(CONFIG_ARCH_RZN1) += ../armv7/rzn1/


