#
# (C) Copyright 2015 Renesas Electronics Europe Ltd
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	:= cpu.o clock.o pinmux.o
obj-$(CONFIG_SPL_BUILD)	+= spl.o
obj-$(CONFIG_CADENCE_DDR_CTRL)	+= ddr_ctrl.o ddr_phy.o
obj-$(CONFIG_DESIGNWARE_ETH)	+= eth.o
